TALISMAN Log file

2018/06/15-04:40:28 : Log start: EVENT

!!! **************************************************
2018/06/15-04:40:28 : !!! Start test, script file: tst-exc-01.script

// Script:    Tst-exc-01.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test exception handler
      6 == Declarations
     15 == Reset
     20 == Test throwing assertion exception
--- Exception caught: ASSERTION: Failing expression: false
        Exception thrown in Line: 747  File: ..\sources\tst_exc.cpp

     23 == Test throwing enforce exception
--- Exception caught: ENFORCE: Failing expression: false
        Exception thrown in Line: 750  File: ..\sources\tst_exc.cpp

     26 == Test throwing error exception
--- Exception caught: USAGE: idType: 3  idGroup: 7  idHelp: 8
        Exception thrown in Line: 753  File: ..\sources\tst_exc.cpp

            >>> id help: 8

     29 == Test throwing platform exception
--- Exception caught: PLATFORM: idType: 4  idGroup: 12  idHelp: 13
        Exception thrown in Line: 756  File: ..\sources\tst_exc.cpp

            >>> id help: 13

     32 == Test throwing failure exception
--- Exception caught: PROGRAM: idType: 5  idGroup: 10  idHelp: 11
        Exception thrown in Line: 759  File: ..\sources\tst_exc.cpp

            >>> id help: 11

     35 == Set the throw tracer on

====== USAGE exception 30145 thrown in line: 753  file: ..\sources\tst_exc.cpp

--- Exception caught: USAGE: idType: 3  idGroup: 7  idHelp: 8
        Exception thrown in Line: 753  File: ..\sources\tst_exc.cpp

            >>> id help: 8

     39 == Test throwing enforce exception

====== ENFORCE exception 143 thrown in line: 750  file: ..\sources\tst_exc.cpp

--- Exception caught: ENFORCE: Failing expression: false
        Exception thrown in Line: 750  File: ..\sources\tst_exc.cpp

     42 == Set the throw tracer off
--- Exception caught: USAGE: idType: 3  idGroup: 7  idHelp: 8
        Exception thrown in Line: 753  File: ..\sources\tst_exc.cpp

            >>> id help: 8

     46 == Test throwing failure exception
--- Exception caught: PROGRAM: idType: 5  idGroup: 10  idHelp: 11
        Exception thrown in Line: 759  File: ..\sources\tst_exc.cpp

            >>> id help: 11

     49 == Create an error message
     52 == Display several versions
Exception: USAGE: +++ Usage error exception +++
        Exception thrown in Line: 12345  File: aFile
 
            >>> id help: 111

--- Exception caught: USAGE: +++ Usage error exception +++
        Exception thrown in Line: 12345  File: aFile

            >>> id help: 111

**** Test header USAGE: +++ Usage error exception +++
        Exception thrown in Line: 12345  File: aFile
 *** follower ***
            >>> id help: 111

     57 == Log the error
2018/06/15-04:40:28 : USAGE: +++ Usage error exception +++
        Exception thrown in Line: 12345  File: aFile

     61 == verify memory leak
//
// ==========>>> Must display test OK
//

2018/06/15-04:40:28 : !!! End of test, script file: tst-exc-01.script
!!! **************************************************

!!! --------------------
!!!  Test ended
     Test statistics:   Test files 1  Test cases 15  Test commands 29  Test lines 71
     Test ending condition: No failures found.

2018/06/15-04:40:28 : Log end: EVENT
