// Script:    Tst-main-02.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality

// Test throw, correctly catch and rethrow program exceptions 

// Due to unhandled exception must cancel and display 4 errors

//
// ==========>>> Must stop with 4 errors and disaster
//

== Declarations
=DeclareParameter  idAssert     int    154
=DeclareParameter  idEnforce    int    153
=DeclareParameter  typeAssert   int      1
=DeclareParameter  typeEnforce  int      2
=DeclareParameter  typeError    int      3
=DeclareParameter  typePlatform int      4
=DeclareParameter  typeFailure  int      5
=DeclareParameter  tstMessage   int   30147

=DeclareParameter  selectError   int     1
=DeclareParameter  selectFailure int     2

== Test correct program error exception catcher, missing recovery 'c'
=Throw              selectError  0  -1  "test"
=ExceptionProgram   typeError    tstMessage 
// Should never reach this point

