TALISMAN Log file

2018/06/15-04:40:28 : Log start: EVENT

!!! **************************************************
2018/06/15-04:40:28 : !!! Start test, script file: tst-exc-08.script

// Script:    Tst-main-08.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality
// Test throw, do not catch due to missing recovery command
//
// ==========>>> Must stop with 4 errors and disaster
//
     12 == Declarations
     24 == Test missing program error exception catcher, blank line

>>> 1    Line 25  Tester caught a program exception, context 0 >>
--- EXC: PROGRAM: Thrown while testing
        Exception thrown in Line: 837  File: ..\sources\tst_exc.cpp

>>> 2    Line 26  Missing program exception catch command. 

######  Unexpected program exception !!!!!

    3    Line 26  vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv 
>>> 4    Line 26  Test crash: Program will be cancelled.
 


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


>>>DISASTER: Test has been cancelled prior to ending !!!

      At Line: 250  In module: ..\sources\gnrctest.cpp

>>>DISASTER: Starting roll back.


>>>DISASTER: Roll back completed. Program will be canceled now !!!


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


